### ISSUE TITLE
How to install it on pop os

### ISSUE THREAD

**Issue by 4Quatros** [KoboldAI/KoboldAI-Client#106]
Im new to linux and chose pop os to start (been using it for 2 months now). And i cant install Kobold on it as im new to linux. Please teach me how to insatalll

**Comment by henk717** [comment]
Until the next version is out it is probably the easiest to use the development version since it has my new installation routine which is much easier.

KoboldAI is exclusively terminal based, so make sure to have a terminal ready.
First you will want to install CUDA if you have an Nvidia GPU, you do so with this command : sudo apt install system76-cuda-latest

Then clone KoboldAI's github, since we will be using the development version it is going to be : git clone https://github.com/henk717/koboldai

After that you should be setup with the basics and can use your terminal to start ./play.sh to get going, it will automatically download and install everything else it needs within its own folder.

**Comment by henk717** [comment]
This is now upstreamed, people just need to clone the git and run play.sh (As long as you have a working copy of wget and bzip2 and suitable GPU drivers if you plan to use the GPU).
