### ISSUE TITLE
The link does not appear

### ISSUE THREAD

**Issue by Myuless** [KoboldAI/KoboldAI-Client#131]
the link does not appear when I try to log in through the local tunnel, how do I fix it?
![Безымянный](https://user-images.githubusercontent.com/105026747/175742726-ca8033a2-a7db-4a87-9508-844027c7d0d9.png)

**Comment by henk717** [comment]
Localtunnel has been offline since yesterday and can can not be used until loca.lt is back online.
I recommend selecting Cloudflare in the options instead (Which should be the default).

People interested in Localtunnel can track the status here : https://github.com/localtunnel/localtunnel/issues/501

**Comment by Myuless** [comment]
ok thanks and also a question is there any difference between the local tunnel and cloudflare

**Comment by henk717** [comment]
Cloudflare can be blocked by some antivirus products, and you sometimes need to wait a minute before the link works. Once you are connected to it Cloudflare is very reliable.

**Comment by Myuless** [comment]
Ok thanks
