### ISSUE TITLE
WebServer never starts Linux

### ISSUE THREAD

**Issue by KShivum** [KoboldAI/KoboldAI-Client#139]
Hi, so I'm running Kobold AI on Fedora 36 and for some reason the webserver does not start. It'll hang on "Starting webserver..." for what seems like indefinitely (So far it has been an hour). Pressing Control C starts Kobold AI immediately, however, I am not able to connect to the AI from a different device (I'm assuming because the actual web server never started?). Is there a place I should look to find a log on why?

**Comment by henk717** [comment]
Which arguments are you using to start it? Since you are trying to use a different device I assume you are using --remote?
That mode tries to generate a cloudflare link, so you would need cloudflare functional to complete the routine. You could try --host and see if that works, since then it won't setup a remote cloudflare connection and merely unblocks the port.

Also make sure to use play.sh so you use our official dependencies.

**Comment by KShivum** [comment]
> Which arguments are you using to start it? Since you are trying to use a different device I assume you are using --remote? That mode tries to generate a cloudflare link, so you would need cloudflare functional to complete the routine. You could try --host and see if that works, since then it won't setup a remote cloudflare connection and merely unblocks the port.
> 
> Also make sure to use play.sh so you use our official dependencies.

Ah I was being dumb, I just ran play.sh without any arguments. Running it with host caused it to start up basically instantly.
