### ISSUE TITLE
[Feature Request] Contrastive Search

### ISSUE THREAD

**Issue by shinkarom** [KoboldAI/KoboldAI-Client#178]
https://arxiv.org/abs/2210.14140

A new sampler which gives miraculous results when tried in oniine demo. It has two sliders, not just one.

**Comment by vfbd** [comment]
We have already decided not to implement contrastive search for a variety of reasons, including:

- Severe increase in generation time and/or required memory compared to sampling
- The fact that its design is oriented around improving the accuracy of a model's question answering abilities and reducing repetition and not for helping with story creativity, which is ill-suited for story generation since we already have repetition penalty and samplers
- The inability to use temperature and other samplers concurrently with contrastive search because it is not a sampler but a beam search-like technique
- Technical limitations currently making it very difficult to implement on the TPU codebase
