### ISSUE TITLE
Access the browser gui from another computer.

### ISSUE THREAD

**Issue by Delcos** [KoboldAI/KoboldAI-Client#205]
If I want to run the software on a different computer on the same local network, what needs to be changed settings wise to allow this? Thanks :) .

**Comment by SparksSkywere** [comment]
On the host client/server run "remote-play.bat", for me I access via the normal port 5000 with the IP of the server so for example the address you want to input into your URL is "192.168.0.**:5000. If you have firewall issues make sure to open it on the host machine, 

Windows bat:
![image](https://user-images.githubusercontent.com/34066194/221431248-8ed18760-f2bf-4665-998f-6d6ff494afeb.png)

Console on my server:
![image](https://user-images.githubusercontent.com/34066194/221431330-84c9031c-fa6e-40d8-bec4-b01a9299bff6.png)

Firewall: You may also add a UDP using the same port.
![image](https://user-images.githubusercontent.com/34066194/221431461-896ce00e-e307-4557-b045-d636017e6e95.png)

**Comment by Xeddius** [comment]
The "remote" cloudflare/url solution does not work for my use case as I need direct access (IP to IP) on two different machines located within a private network that does not have access to the internet itself. (And can not have access because of security policy.) I just need a simple flag or whitelist option to enable connections on LAN or specific subnet please.

**Comment by henk717** [comment]
--host can be used instead
