### ISSUE TITLE
License

### ISSUE THREAD

**Issue by MikkoMMM** [KoboldAI/KoboldAI-Client#33]
Please add a license file.

**Comment by aviallon** [comment]
I up this very much.
By default, your work is "all rights reserved"

**Comment by meraine** [comment]
I would suggest a strong copyleft license like [AGPLv3](https://www.gnu.org/licenses/agpl-3.0.html):

> The GNU Affero General Public License is a modified version of the ordinary GNU GPL version 3. It has one added requirement: if you run a modified program on a server and let other users communicate with it there, your server must also allow them to download the source code corresponding to the modified version running there.
>
> The purpose of the GNU Affero GPL is to prevent a problem that affects developers of free programs that are often used on servers.

That problem being, that others will take GPLv3 software, modify it, put it on a server, and then prevent users from seeing the changed source code since they're not legally obligated to share it when it's just used over a network connection.

Some other software that use AGPL include: [WriteFreely](https://github.com/writefreely/writefreely), [Mastodon](https://github.com/tootsuite/mastodon), [PeerTube](https://github.com/Chocobozzz/PeerTube), and [Signal](https://github.com/signalapp/Signal-Server). What these projects all have in common is that they're intended for users to self-host their own copy of the software. In particular, I think that AGPL would be a good way to ensure users retain their rights should someone take KoboldAI and try to make an AI Dungeon-like experience with it by hosting it on their own server for others to use.

**Comment by MikkoMMM** [comment]
When you were talking about rights, I first thought it was just about the ideological stance that copyleft is the way to go to achieve software freedom. There are two schools of thought on this (the permissive license camp being the other I'm referring to) and while it might be that it was pretty much a necessity for something like Linux to be copyleft to have happened, for a lot of smaller software we are seeing alternatives cropping up almost left and right. If those alternatives are going to happen anyway, isn't it just spiteful to hamper the efforts of those who subscribe to different ideals by imposing heavy control over source code? Even if that ideal is "money", should we care? KoboldAI developers don't (probably) have the resources to host KoboldAI for remote users to use, so if (hypothetically) somebody does have those and is deterred from that by a license choice, that will be a loss to the player base.

But then I thought of something that does speak for AGPL or similar for server-based things. All those issues that AI Dungeon is currently dealing with. If the modifications to the code aren't published, that can then be a legal weapon in a scenario where there have been controversial changes to it, once discovered. And if they are published, at least the users can determine exactly how the system works. But of course this is all assuming they didn't just make their own AI Dungeon clone. If they have the resources to host such a thing, they would have for development, I'd imagine, as well.

Anyway, I'm not a developer of KoboldAI so you could just ignore my ramblings.

**Comment by tralezab** [comment]
AGPLv3 is REALLY good, I also recommend that.

**Comment by aviallon** [comment]
AGPLv3 makes a lot of sense for this project, indeed. And I would be ready to spend a lot of time improving the project if it were opensource (because currently, it is only source available, but we have no rights to modify or even share the code ourselves, even locally...)

**Comment by henk717** [comment]
From my understanding AGPL would require us to publish the source code of CUDA which is not possible, so we'd have to give up GPU support. I like the sentiment of people not being able to make a closed source service based on KoboldAI though, but i'd like it to be liberal enough that developers / modders aren't required to do this for private use. Something like it only being required if you run an unattended service, if it requires you manually starting a developer instance i think it would be fine to allow closed source usage until you feel ready to share the code.

We'd need something like a hybrid of LGPL and AGPL, or just our own custom license since it seems a lot of the big well known ones aren't an exact fit.

**Comment by aviallon** [comment]
@henk717 AGPL doesn't prevent you from using CUDA at all! It only applies to the code you wrote, not to the libraries you use.

**Comment by aviallon** [comment]
However, since it's been half a month without any answer from the maintainer, I think I'll rewrite KoboldAI from scratch... It'll be a good exercise, and it should also make it more maintainable (everything in one source file, seriously?).

**Comment by aviallon** [comment]
> We'd need something like a hybrid of LGPL and AGPL, or just **our own custom license** since it seems a lot of the big well known ones aren't an exact fit.

Beware! Writing a license without advice from a lawyer can be dangerous... very dangerous. It can backfire REALLY hard. There has been examples of that in the past.

**Comment by henk717** [comment]
@aviallon Trusting your judgement on the CUDA part it would be quite a fitting license for us, but it does have one requirement the project currently does not meet. The ability to download the source code from the interface because of this line ' your modified version must prominently offer all users interacting with it remotely through a computer network (if your version supports such interaction) an opportunity to receive the Corresponding Source of your version by providing access to the Corresponding Source from a network server at no charge'.

To do that effectively and complicity without being a massive pain to developers sharing test links we'd need a button that can automatically zip up a copy of the game without exposing user data / models and offer it as a download in the browser.

I love the spirit of the AGPL in terms of people not being able to offer this as a closed service, but in my eyes it would be more practical to have a license that allows attended instances to be exempt from the sharing rule. That way if you are developing and have an attended development instance running and your just sharing a test link you don't have to worry about file distribution, while when you are putting this as a background task on a server you'd have to meet this requirement and provide a link to the source (Which then more easily can just be a github link you specify somewhere).

Either the software based solution of automating the requirement, or the exception would allow users, modders and developers to use the software worry free in a very liberal way. While still protecting the project from rogue closed services.

**Comment by KoboldAI** [comment]
AGPLv3 license added.
