### ISSUE TITLE
ModuleNotFoundError: No module named 'ansi2html'

### ISSUE THREAD

**Issue by AlexFenix33** [KoboldAI/KoboldAI-Client#354]
Give back that result

`Traceback (most recent call last):
  File "aiserver.py", line 26, in <module>
    from ansi2html import Ansi2HTMLConverter
ModuleNotFoundError: No module named 'ansi2html'`

**Comment by Vendaciousness** [comment]
```
pip install ansi2html --no-cache
```
Worked for me. Then it named a few more dependencies that were missing and I did the same command until it eventually ran. This worked for me on both the main branch and the dev.

**Comment by henk717** [comment]
When using our official runtime nothing should be missing (install_requirements.bat and then play.bat)
That said I recommend using the offline installer (For United its on my git) to get everything setup instead of install_requirements.bat since its a smaller download and then its guaranteed to copy everything over correctly.
