### ISSUE TITLE
Kobold AI won't start

### ISSUE THREAD

**Issue by slimetunnel** [KoboldAI/KoboldAI-Client#360]
Hi! I looked this up by copy and pasting the whole thing, but here's what's up.

> 
> Runtime launching in B: drive mode
> Traceback (most recent call last):
>   File "aiserver.py", line 30, in <module>
>     import attention_bias
>   File "C:\KoboldAI\attention_bias.py", line 16, in <module>
>     import torch
>   File "B:\python\lib\site-packages\torch\__init__.py", line 122, in <module>
>     raise err
> OSError: [WinError 127] The specified procedure could not be found. Error loading "B:\python\lib\site-packages\torch\lib\nvfuser_codegen.dll" or one of its dependencies.
> (base) C:\KoboldAI>

How do I fix this or get around it?

**Comment by Mat2032** [comment]
Hi !
I have the same problem after installing Kobold AI with the offline installer.
I have the impression that the script will look for a file '__init__.py" in the B:\ disk but which does not exist and which should not be selected because you installed it on the C:\ disk ( and personally I installed it on my H:\ drive)
so I think there is an error in the code that causes inference_model.py to look for the torch module but to locate it on disk B:\ but which does not exist...
![Capture d'écran 2023-08-11 214525](https://github.com/KoboldAI/KoboldAI-Client/assets/51493013/e41deed3-807d-4cc1-80a6-f7665a54f35b)

**Comment by Mat2032** [comment]
Okay I managed to fix it for me:
- Launch "install_requirements.bat" as administrator
- Delete everything (choice 1)
- Installation at the root of a disk (choice 1)
- Everything settles down
- I restart "play.bat" and everything starts and the browser page opens in localhost:5000

**Comment by henk717** [comment]
This is indeed normal, United needs the offline installer snapshots until 2.0 is out.
