### ISSUE TITLE
Remove the CIA spyware

### ISSUE THREAD

**Issue by jummin** [KoboldAI/KoboldAI-Client#396]
requirements.txt has a github project called mkultra as a requirement.

https://github.com/corolla-johnson/mkultra

"mkultra is a prompt tuning toolkit for GPT-2 and GPT-Neo. Prompt tuning injects a string of 20-100 special tokens into the context in order to influence text generation. These tokens are trained on a corpus much like a finetune, but take up a fraction of the space. The Neuromancer example is only 401kb for 100 tokens."

What is even the point of this? What "special tokens" is it injecting?

**Comment by henk717** [comment]
Its a dependency used to create softprompts with, those are files to steer the AI in a certain direction.
If you hate it, modify the requirements on your own copy so it won't install it and you won't miss out on anything, we merely include it for completeness so that people can tune their own softprompts locally.

It basically allows you to grab the essence of larger texts and then inject that in to the story, the author could have picked a much better name for it but it has nothing to do with the CIA's MKUltra.
