### ISSUE TITLE
I ran into an OS Error [WinError 10048]

### ISSUE THREAD

**Issue by Sushimiyaaa** [KoboldAI/KoboldAI-Client#400]
OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted
What do I do?

**Comment by henk717** [comment]
This happens if another process is already running on port 5000, this is commonly people who have another copy of KoboldAI open.
If you are following one of those terrible guides that tell you to run the KoboldAI (Remote) shortcut after loading a model this would be why.

So couple of steps to check:
1. When KoboldAI is not open visit http://localhost:5000 in your browser to see if anything pops up.
2. Open KoboldAI in the mode you want to run (If you want a cloudflare link immediately use the remote mode).
3. Visit KoboldAI's link to load a model, and then enjoy the model either in our UI or in your third party UI / site.

If 5000 is being blocked by another program and you can't get that program to change you can also use --port with a different port number in your KoboldAI shortcut or command prompt.

**Comment by Sushimiyaaa** [comment]
Hi! Thanks for getting back to me, could you explain to me how to use a different port number for KoboldAI?
