### ISSUE TITLE
Running on linux

### ISSUE THREAD

**Issue by TheMcSebi** [KoboldAI/KoboldAI-Client#64]
I was trying to get this to run on Pop OS when I encountered an issue.
The installation steps all went fine, but when I was first tried to start the game using play-cuda.sh it didn't work because of this issue: https://github.com/KoboldAI/KoboldAI-Client/blob/91efd9a9466de0b756563d52d00360d6f2d90a68/docker-cuda/Dockerfile#L7
Resolved that by commenting out the line, because xorg was already installed.
Now when trying to run it I get this error:

Error response from daemon: error gathering device information while adding custom device "/dev/kfd": no such file or directory

Found out this might have something to do with rocm, which I don't have installed (Because I'm trying to run this on a 1080Ti).
Now I wonder if running this on linux is even supported since all the instructions are made for windows :)
I have to mention though, that it does run flawlessly in my Installation of Windows. No issues at any process step. Only tried the gpt neo 2.7B parameter set so far and runs fine on 11GB VRAM. Thanks for all the work that has already been put into this.

**Comment by henk717** [comment]
I do not have nvidia so my attempt at play-cuda.sh was completely blind and apparently unsuccesful. This will be quite tricky to solve over github since we will have to find out what ends up working one on one.

For that one line don't comment it out and add the following above it and then move these two lines to the bottom of the script:
`USER root`

This should elevate its permission to root at the last moment and install X11 (this is inside the docker not on your real installation). You need this inside the docker instance so it can draw the file selection window properly.

The missing device is most likely an issue with me plainly copying my amd version hoping it would work. Try removing that from the cuda docker files.

If it still gives issues i recommend joining the kobold discord at https://discord.gg/UCyXV7NssH so we can try and fix this one on one (I am Henky!! there).

**Comment by AngryBeeSec** [comment]
Hi on the topic Linux, to get KoboldAI to run on Arch you may need to modify the docker-compose.yml for it to see your nvidia GPU. If you don't it may lock up on large models.

version: "3.2"
services:
  koboldai:
    build: .
    environment:
      - DISPLAY=${DISPLAY} 
    network_mode: "host"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../:/content/
      - $HOME/.Xauthority:/home/micromamba/.Xauthority:rw
    devices:
      - /dev/dri
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-uvm:/dev/nvidia-uvm
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            device_ids: ['0']
            capabilities: [gpu]
    group_add:
      - video

**Comment by henk717** [comment]
Feel free to issue that as a commit here on github, i don't have all the parts for my nvidia gpu yet.

**Comment by henk717** [comment]
The old one wasn't working on the GPU's in general, leaving this issue open for further testing but i expect this to work well for most people!
