### ISSUE TITLE
Can work in android?

### ISSUE THREAD

**Issue by Jolucal** [KoboldAI/KoboldAI-Client#88]
I just want to play this, but i don't know this work in android :(

**Comment by henk717** [comment]
The program itself can not run on Android, but you can run it for free on Google's servers and then play it in your phone browser.
To do this visit https://henk.tech/colabkobold , put your browser in desktop mode on the colab (they have a bug that otherwise erases them) and follow the instructions on screen. It will take a while to load so its not very suitable for quick breaks but it will be usable especially if you have a good keyboard like Gboard.
