### ISSUE TITLE
Shinen model won't launch

### ISSUE THREAD

**Issue by ObiJuanKenobi2223** [KoboldAI/KoboldAI-Client#89]
trying to open the shinen model in colab gives me
`OSError: /usr/local/lib/python3.7/dist-packages/torch/lib/libtorch_global_deps.so: cannot open shared object file: No such file or directory`

**Comment by henk717** [comment]
I have just loaded up Shinen's colab succesfully (For the record, this is https://colab.research.google.com/drive/1-7Lkj-np2DaSnmq1OdPYkel6W2rh4E-0?usp=sharing#sandboxMode=true in case you found an unofficial one somewhere online).
If you also used this version I expect you ran into a rare issue with pip not downloading torch correctly.

Best thing you can do is go to the Runtime -> Session tab and make sure nothing is running. Then try it again, since it worked for me it should work for you to.
