### ISSUE TITLE
Feature: repetition penalty slope

### ISSUE THREAD

**Issue by shinkarom** [KoboldAI/KoboldAI-Client#93]
Let's face it. Repetition penalty 1.2 is good, but only for very short texts. Later it starts selecting irrelevant words, because the tokens need to be distinct from everything that was before.
NovelAI has Repetition Penalty Slope, where tokens further from the end of context don't need to be so distinct (meaning repetition penalty gradually fades to 0 the further from context the tokens are; the slope regulates the speed of fading).

**Comment by henk717** [comment]
We are aware of it and its indeed something i like to see as well. Unfortunately transformers doesn't have this as far as i could see so its not as simple as just hooking up a parameter and be done with it.

It almost certainly won't be in the next release (since its feature frozen, development happens so fast at times it would otherwise not be released) which is right around the corner but for the one after thst i'd love to see it in. So ill keep this open until its implemented in the development branch.

**Comment by henk717** [comment]
We changed our mind, it was finished in time for the next release and I think it's important enough to include it. So it will push the release back a little bit but then you will be able to use it right as it comes out.
If you want to help test check out the United branch on my github.

**Comment by shinkarom** [comment]
Thank you very much.

**Comment by henk717** [comment]
Implemented in 1.17
